/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type AdminFees = {
  iboCreationFee: beet.bignum
  lockupFee: beet.bignum
  gateAdditionFee: beet.bignum
}

/**
 * @category userTypes
 * @category generated
 */
export const adminFeesBeet = new beet.BeetArgsStruct<AdminFees>(
  [
    ['iboCreationFee', beet.u64],
    ['lockupFee', beet.u64],
    ['gateAdditionFee', beet.u64],
  ],
  'AdminFees'
)
