/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type Cuts = {
  purchaseCut: beet.bignum
  resaleCut: beet.bignum
}

/**
 * @category userTypes
 * @category generated
 */
export const cutsBeet = new beet.BeetArgsStruct<Cuts>(
  [
    ['purchaseCut', beet.u64],
    ['resaleCut', beet.u64],
  ],
  'Cuts'
)
