/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type UserFees = {
  bondClaimFee: beet.bignum
  bondPurchaseFee: beet.bignum
  bondSplitFee: beet.bignum
}

/**
 * @category userTypes
 * @category generated
 */
export const userFeesBeet = new beet.BeetArgsStruct<UserFees>(
  [
    ['bondClaimFee', beet.u64],
    ['bondPurchaseFee', beet.u64],
    ['bondSplitFee', beet.u64],
  ],
  'UserFees'
)
