[features]
seeds = false
skip-lint = false
[programs.localnet]
dark_bonds = "8ZP1cSpVPVPp5aeake5f1BtgW1xv1e39zkoG8bWobbwV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/wincentdulkowski/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/dark-bonds.ts"
nft = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/vertex-nft.test.ts"
mint = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/mint-test.ts"