/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import * as beet from '@metaplex-foundation/beet'

/**
 * Arguments used to create {@link BondPointer}
 * @category Accounts
 * @category generated
 */
export type BondPointerArgs = {
  bondAddress: web3.PublicKey
}

export const bondPointerDiscriminator = [130, 185, 53, 150, 251, 69, 13, 73]
/**
 * Holds the data for the {@link BondPointer} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class BondPointer implements BondPointerArgs {
  private constructor(readonly bondAddress: web3.PublicKey) {}

  /**
   * Creates a {@link BondPointer} instance from the provided args.
   */
  static fromArgs(args: BondPointerArgs) {
    return new BondPointer(args.bondAddress)
  }

  /**
   * Deserializes the {@link BondPointer} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [BondPointer, number] {
    return BondPointer.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link BondPointer} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<BondPointer> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find BondPointer account at ${address}`)
    }
    return BondPointer.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      '8ZP1cSpVPVPp5aeake5f1BtgW1xv1e39zkoG8bWobbwV'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, bondPointerBeet)
  }

  /**
   * Deserializes the {@link BondPointer} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [BondPointer, number] {
    return bondPointerBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link BondPointer} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return bondPointerBeet.serialize({
      accountDiscriminator: bondPointerDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link BondPointer}
   */
  static get byteSize() {
    return bondPointerBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link BondPointer} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      BondPointer.byteSize,
      commitment
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link BondPointer} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === BondPointer.byteSize
  }

  /**
   * Returns a readable version of {@link BondPointer} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      bondAddress: this.bondAddress.toBase58(),
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const bondPointerBeet = new beet.BeetStruct<
  BondPointer,
  BondPointerArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['bondAddress', beetSolana.publicKey],
  ],
  BondPointer.fromArgs,
  'BondPointer'
)
