/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link Bond}
 * @category Accounts
 * @category generated
 */
export type BondArgs = {
  owner: web3.PublicKey
  idx: number
  swapPrice: beet.bignum
  totalClaimable: beet.bignum
  maturityDate: beet.bignum
  lastClaimed: beet.bignum
  bondStart: beet.bignum
  matureOnly: boolean
}

export const bondDiscriminator = [224, 128, 48, 251, 182, 246, 111, 196]
/**
 * Holds the data for the {@link Bond} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class Bond implements BondArgs {
  private constructor(
    readonly owner: web3.PublicKey,
    readonly idx: number,
    readonly swapPrice: beet.bignum,
    readonly totalClaimable: beet.bignum,
    readonly maturityDate: beet.bignum,
    readonly lastClaimed: beet.bignum,
    readonly bondStart: beet.bignum,
    readonly matureOnly: boolean
  ) {}

  /**
   * Creates a {@link Bond} instance from the provided args.
   */
  static fromArgs(args: BondArgs) {
    return new Bond(
      args.owner,
      args.idx,
      args.swapPrice,
      args.totalClaimable,
      args.maturityDate,
      args.lastClaimed,
      args.bondStart,
      args.matureOnly
    )
  }

  /**
   * Deserializes the {@link Bond} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [Bond, number] {
    return Bond.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link Bond} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<Bond> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find Bond account at ${address}`)
    }
    return Bond.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      '8ZP1cSpVPVPp5aeake5f1BtgW1xv1e39zkoG8bWobbwV'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, bondBeet)
  }

  /**
   * Deserializes the {@link Bond} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [Bond, number] {
    return bondBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link Bond} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return bondBeet.serialize({
      accountDiscriminator: bondDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link Bond}
   */
  static get byteSize() {
    return bondBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link Bond} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      Bond.byteSize,
      commitment
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link Bond} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === Bond.byteSize
  }

  /**
   * Returns a readable version of {@link Bond} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      owner: this.owner.toBase58(),
      idx: this.idx,
      swapPrice: (() => {
        const x = <{ toNumber: () => number }>this.swapPrice
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      totalClaimable: (() => {
        const x = <{ toNumber: () => number }>this.totalClaimable
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      maturityDate: (() => {
        const x = <{ toNumber: () => number }>this.maturityDate
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      lastClaimed: (() => {
        const x = <{ toNumber: () => number }>this.lastClaimed
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      bondStart: (() => {
        const x = <{ toNumber: () => number }>this.bondStart
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      matureOnly: this.matureOnly,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const bondBeet = new beet.BeetStruct<
  Bond,
  BondArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['owner', beetSolana.publicKey],
    ['idx', beet.u32],
    ['swapPrice', beet.u64],
    ['totalClaimable', beet.u64],
    ['maturityDate', beet.i64],
    ['lastClaimed', beet.i64],
    ['bondStart', beet.i64],
    ['matureOnly', beet.bool],
  ],
  Bond.fromArgs,
  'Bond'
)
