/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import { PurchasePeriod, purchasePeriodBeet } from '../types/PurchasePeriod'

/**
 * @category Instructions
 * @category AddLockup
 * @category generated
 */
export type AddLockupInstructionArgs = {
  lockupDuration: beet.bignum
  lockupApy: beet.bignum
  matureOnly: boolean
  purchasePeriod: PurchasePeriod
}
/**
 * @category Instructions
 * @category AddLockup
 * @category generated
 */
export const addLockupStruct = new beet.FixableBeetArgsStruct<
  AddLockupInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['lockupDuration', beet.i64],
    ['lockupApy', beet.u64],
    ['matureOnly', beet.bool],
    ['purchasePeriod', purchasePeriodBeet],
  ],
  'AddLockupInstructionArgs'
)
/**
 * Accounts required by the _addLockup_ instruction
 *
 * @property [_writable_, **signer**] admin
 * @property [_writable_] ibo
 * @property [_writable_] lockup
 * @property [_writable_] master
 * @category Instructions
 * @category AddLockup
 * @category generated
 */
export type AddLockupInstructionAccounts = {
  admin: web3.PublicKey
  ibo: web3.PublicKey
  lockup: web3.PublicKey
  master: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const addLockupInstructionDiscriminator = [
  147, 104, 186, 239, 85, 181, 98, 24,
]

/**
 * Creates a _AddLockup_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category AddLockup
 * @category generated
 */
export function createAddLockupInstruction(
  accounts: AddLockupInstructionAccounts,
  args: AddLockupInstructionArgs,
  programId = new web3.PublicKey('8ZP1cSpVPVPp5aeake5f1BtgW1xv1e39zkoG8bWobbwV')
) {
  const [data] = addLockupStruct.serialize({
    instructionDiscriminator: addLockupInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.admin,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.ibo,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.lockup,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.master,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
