/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category Lock
 * @category generated
 */
export type LockInstructionArgs = {
  lockWithdraws: boolean
  lockLockupAddition: boolean
}
/**
 * @category Instructions
 * @category Lock
 * @category generated
 */
export const lockStruct = new beet.BeetArgsStruct<
  LockInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['lockWithdraws', beet.bool],
    ['lockLockupAddition', beet.bool],
  ],
  'LockInstructionArgs'
)
/**
 * Accounts required by the _lock_ instruction
 *
 * @property [_writable_, **signer**] admin
 * @property [_writable_] ibo
 * @category Instructions
 * @category Lock
 * @category generated
 */
export type LockInstructionAccounts = {
  admin: web3.PublicKey
  ibo: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const lockInstructionDiscriminator = [21, 19, 208, 43, 237, 62, 255, 87]

/**
 * Creates a _Lock_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category Lock
 * @category generated
 */
export function createLockInstruction(
  accounts: LockInstructionAccounts,
  args: LockInstructionArgs,
  programId = new web3.PublicKey('8ZP1cSpVPVPp5aeake5f1BtgW1xv1e39zkoG8bWobbwV')
) {
  const [data] = lockStruct.serialize({
    instructionDiscriminator: lockInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.admin,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.ibo,
      isWritable: true,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
