/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * @category Instructions
 * @category Split
 * @category generated
 */
export type SplitInstructionArgs = {
  percentNew: number
  iboAddress: web3.PublicKey
  bondIdx: number
}
/**
 * @category Instructions
 * @category Split
 * @category generated
 */
export const splitStruct = new beet.BeetArgsStruct<
  SplitInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['percentNew', beet.u16],
    ['iboAddress', beetSolana.publicKey],
    ['bondIdx', beet.u32],
  ],
  'SplitInstructionArgs'
)
/**
 * Accounts required by the _split_ instruction
 *
 * @property [_writable_, **signer**] owner
 * @property [_writable_] bond
 * @property [_writable_] bondAtaOld
 * @property [_writable_] bondAtaNew
 * @property [_writable_] newBond
 * @property [_writable_] master
 * @property [_writable_] ibo
 * @category Instructions
 * @category Split
 * @category generated
 */
export type SplitInstructionAccounts = {
  owner: web3.PublicKey
  bond: web3.PublicKey
  bondAtaOld: web3.PublicKey
  bondAtaNew: web3.PublicKey
  newBond: web3.PublicKey
  master: web3.PublicKey
  ibo: web3.PublicKey
  tokenProgram?: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const splitInstructionDiscriminator = [
  124, 189, 27, 43, 216, 40, 147, 66,
]

/**
 * Creates a _Split_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category Split
 * @category generated
 */
export function createSplitInstruction(
  accounts: SplitInstructionAccounts,
  args: SplitInstructionArgs,
  programId = new web3.PublicKey('8ZP1cSpVPVPp5aeake5f1BtgW1xv1e39zkoG8bWobbwV')
) {
  const [data] = splitStruct.serialize({
    instructionDiscriminator: splitInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.owner,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.bond,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.bondAtaOld,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.bondAtaNew,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.newBond,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.master,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.ibo,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
