/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category UpdateRate
 * @category generated
 */
export type UpdateRateInstructionArgs = {
  iboIdx: beet.bignum
  newRate: beet.bignum
}
/**
 * @category Instructions
 * @category UpdateRate
 * @category generated
 */
export const updateRateStruct = new beet.BeetArgsStruct<
  UpdateRateInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['iboIdx', beet.u64],
    ['newRate', beet.u64],
  ],
  'UpdateRateInstructionArgs'
)
/**
 * Accounts required by the _updateRate_ instruction
 *
 * @property [_writable_, **signer**] admin
 * @property [_writable_] ibo
 * @property [_writable_] master
 * @category Instructions
 * @category UpdateRate
 * @category generated
 */
export type UpdateRateInstructionAccounts = {
  admin: web3.PublicKey
  ibo: web3.PublicKey
  master: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const updateRateInstructionDiscriminator = [
  24, 225, 53, 189, 72, 212, 225, 178,
]

/**
 * Creates a _UpdateRate_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category UpdateRate
 * @category generated
 */
export function createUpdateRateInstruction(
  accounts: UpdateRateInstructionAccounts,
  args: UpdateRateInstructionArgs,
  programId = new web3.PublicKey('8ZP1cSpVPVPp5aeake5f1BtgW1xv1e39zkoG8bWobbwV')
) {
  const [data] = updateRateStruct.serialize({
    instructionDiscriminator: updateRateInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.admin,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.ibo,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.master,
      isWritable: true,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
