/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category AddTree
 * @category generated
 */
export type AddTreeInstructionArgs = {
  iboIdx: number
  treeIdx: number
  depth: number
}
/**
 * @category Instructions
 * @category AddTree
 * @category generated
 */
export const addTreeStruct = new beet.BeetArgsStruct<
  AddTreeInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['iboIdx', beet.u32],
    ['treeIdx', beet.u8],
    ['depth', beet.u8],
  ],
  'AddTreeInstructionArgs'
)
/**
 * Accounts required by the _addTree_ instruction
 *
 * @property [_writable_, **signer**] admin
 * @property [_writable_] ibo
 * @property [_writable_] tree
 * @category Instructions
 * @category AddTree
 * @category generated
 */
export type AddTreeInstructionAccounts = {
  admin: web3.PublicKey
  ibo: web3.PublicKey
  tree: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const addTreeInstructionDiscriminator = [
  126, 173, 7, 207, 221, 56, 90, 149,
]

/**
 * Creates a _AddTree_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category AddTree
 * @category generated
 */
export function createAddTreeInstruction(
  accounts: AddTreeInstructionAccounts,
  args: AddTreeInstructionArgs,
  programId = new web3.PublicKey('8ZP1cSpVPVPp5aeake5f1BtgW1xv1e39zkoG8bWobbwV')
) {
  const [data] = addTreeStruct.serialize({
    instructionDiscriminator: addTreeInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.admin,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.ibo,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tree,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
