/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category RemoveGate
 * @category generated
 */
export type RemoveGateInstructionArgs = {
  iboIdx: number
  lockupIdx: number
}
/**
 * @category Instructions
 * @category RemoveGate
 * @category generated
 */
export const removeGateStruct = new beet.BeetArgsStruct<
  RemoveGateInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['iboIdx', beet.u32],
    ['lockupIdx', beet.u32],
  ],
  'RemoveGateInstructionArgs'
)
/**
 * Accounts required by the _removeGate_ instruction
 *
 * @property [_writable_, **signer**] admin
 * @property [_writable_] ibo
 * @property [] lockup
 * @property [_writable_] gate
 * @category Instructions
 * @category RemoveGate
 * @category generated
 */
export type RemoveGateInstructionAccounts = {
  admin: web3.PublicKey
  ibo: web3.PublicKey
  lockup: web3.PublicKey
  gate: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const removeGateInstructionDiscriminator = [
  245, 146, 197, 200, 18, 28, 105, 56,
]

/**
 * Creates a _RemoveGate_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category RemoveGate
 * @category generated
 */
export function createRemoveGateInstruction(
  accounts: RemoveGateInstructionAccounts,
  args: RemoveGateInstructionArgs,
  programId = new web3.PublicKey('8ZP1cSpVPVPp5aeake5f1BtgW1xv1e39zkoG8bWobbwV')
) {
  const [data] = removeGateStruct.serialize({
    instructionDiscriminator: removeGateInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.admin,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.ibo,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.lockup,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.gate,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
