/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link Vertex}
 * @category Accounts
 * @category generated
 */
export type VertexArgs = {
  end: boolean
  subIdx: number
  empty: number[] /* size: 10 */
}

export const vertexDiscriminator = [211, 89, 24, 165, 223, 188, 200, 73]
/**
 * Holds the data for the {@link Vertex} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class Vertex implements VertexArgs {
  private constructor(
    readonly end: boolean,
    readonly subIdx: number,
    readonly empty: number[] /* size: 10 */
  ) {}

  /**
   * Creates a {@link Vertex} instance from the provided args.
   */
  static fromArgs(args: VertexArgs) {
    return new Vertex(args.end, args.subIdx, args.empty)
  }

  /**
   * Deserializes the {@link Vertex} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [Vertex, number] {
    return Vertex.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link Vertex} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<Vertex> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find Vertex account at ${address}`)
    }
    return Vertex.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      '8ZP1cSpVPVPp5aeake5f1BtgW1xv1e39zkoG8bWobbwV'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, vertexBeet)
  }

  /**
   * Deserializes the {@link Vertex} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [Vertex, number] {
    return vertexBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link Vertex} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return vertexBeet.serialize({
      accountDiscriminator: vertexDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link Vertex}
   */
  static get byteSize() {
    return vertexBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link Vertex} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      Vertex.byteSize,
      commitment
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link Vertex} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === Vertex.byteSize
  }

  /**
   * Returns a readable version of {@link Vertex} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      end: this.end,
      subIdx: this.subIdx,
      empty: this.empty,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const vertexBeet = new beet.BeetStruct<
  Vertex,
  VertexArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['end', beet.bool],
    ['subIdx', beet.u8],
    ['empty', beet.uniformFixedSizeArray(beet.u8, 10)],
  ],
  Vertex.fromArgs,
  'Vertex'
)
